name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ${{ secrets.EC2_PROJECT_PATH }}
          git pull origin main
          docker stop inference-api || true
          docker rm inference-api || true
          docker build -t scalable-inference-api .
          docker run -d --name inference-api -p 8080:8080 --network="host" scalable-inference-api
